### PR TITLE
Return an error for non-200 status code from validator

### LINKED ISSUE #2: validator.w3.org/nu ip blocked errors are not handled
Thanks for this helpful module!

We recently bumped up against the rate limit for the validator.w3.org/nu which [is cited as 500 requests within a 10-minute interval](http://www.w3.org/Help/abuse-info/re-reqs.html), causing us to receive a 403 response from the api. However it took us some time to debug this because the relevant code [here](https://github.com/zrrrzzt/html-validator/blob/master/index.js#L50-L60) does not handle the 403 response.

When the rate limit is hit, the `error` from the request is null and the `result` is an HTML error page. On L56, if the format option is specified as json, the module tries to parse that html string as json, causing it to throw a JSON.parse error. It wasn't clear that the parse error was related to the rate limit.

Would you want this module to handle that case? One suggestion would be to return a more descriptive error if the response status code is anything but 200, e.g.

```js
if (response && response.statusCode !== 200) {
  return callback(new Error('Non-200 statusCode from validator api'), null);
}
```

If that sounds good I can float a PR.

### PR DESCRIPTION
**Pull request by danpaz**
@zrrrzzt Resolves #2. Doesn't do anything to address the rate limit, but provides a more helpful error message for the user to identify the problem.

### CODE REVIEW

**Comment by zrrrzzt** [comment]
@danpaz thx a lot for the pr
I will publish an update to npm tomorrow

**Comment by danpaz** [comment]
No problem and thanks for the quick turnaround!

**Comment by zrrrzzt** [comment]
Haven't done anything with this module for ages. Ended up doing a full makeover.  Changed your addition a bit @danpaz 
```
if (response && response.statusCode !== 200) {
  return callback(new Error('Validator returned unexpected statuscode: ' + response.statusCode), null)
}
```

**Comment by danpaz** [comment]
Looks good!

**Pull request merged**
